### ISSUE TITLE
BUILD FUNCTION: is_booked()

### ISSUE THREAD

**Issue by asardie** [asardie/Calendar#22]
```
prototype:  def is_booked(event_id) -> bool:
args: event_id,  from list events function
return: True if event has two attendees.
```

**Comment by asardie** [comment]
this function needs to loop through the events returned by list_events():

**Comment by josekgobJHB** [comment]
does this function receive the list from list_events or does it receive an
event_id of a specific event for which it should check the number of
attendees ?
